# Generated by Django 3.1.2 on 2020-12-23 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_productorder_vendor'),
    ]

    operations = [
        migrations.AddField(
            model_name='productorder',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.product'),
        ),
    ]
